### ISSUE TITLE
how to use biogui with docker mpi and cluster

### ISSUE THREAD

**Issue by deo999** [mjoppich/bioGUI#3]
how to use biogui with docker mpi and cluster

**Comment by mjoppich** [comment]
Hi,

could you elaborate your question a bit more?

Do you want to know how to use bioGUI within a docker container, or how to run docker containers from a bioGUI template?

Thanks,

Markus

**Comment by deo999** [comment]
i want to know how to run bioGUI with docker after converting a command line tool into biogui

**Comment by mjoppich** [comment]
So if I understand you correctly, you have a docker container in which you want to run a command line tool using bioGUI?

Then the first step would be to have a template for your command line tool (which you apparently have).
Then install bioGUI into the docker container and make the template available to bioGUI (place it into the templates directory). Make sure your command line tool is also installed such that the bioGUI template can find it (put it in the $PATH, etc).

You also want to put bioGUI into your $PATH variable I guess.

Now you must get the IP address of your computer (the one which will run the docker container). Make sure that your computer runs an X11 server (Linux and Mac do run one anyway, for Windows install XcvSrv or Xming and start the program).

Then you can launch your docker container with

`docker run -ti --rm -e DISPLAY=<ip>:0.0 <imagename> <pathtobioGUI>`

where you replace <ip> with your IP address, <imagename> with the docker image name to execute and <pathtobioGUI> with the path to bioGUI.

Or do you want to know how to run a command line program in docker using bioGUI?

Then simply run

`docker run -ti -v ~/myprog:/home/bindmount/ --rm <imagename> <programcall>`

where <imagename> is your docker image and <programcall> is the program with arguments you want to call, e.g. Rscript do_analysis.R .
Make sure to bind your volume accordingly. If your script resides in ~/myprog on your computer, and you bind that dir to /home/bindmount/ in docker, your program call will become Rscript /home/bindmount/do_analysis.R .

I hope this helps,

Markus

**Comment by mjoppich** [comment]
You can have a look at the circlator template:

https://github.com/mjoppich/bioGUI/blob/master/templates/circlator_docker.gui

Circlator is provided via a docker container. The Circlator template has the possibility to pull a docker container, perform the progcheck command of Circlator to test the container, as well as to run Circlator on given input.

**Comment by mjoppich** [comment]
No further response -> closed.
